### ISSUE TITLE
Opengl on gnome wont stop running in 1920x1043 when in 1080p

### ISSUE THREAD

**Issue by LethalManBoob** [tx00100xt/SeriousSamClassic-VK#22] opened 2023-05-08 09:37 UTC
Latest arch build Fine on vulkan, fine on kde not fine on gnome. also let me know where to find the logs

**Comment by tx00100xt** [comment] 2023-05-08 15:05
SeriousSam.log Here:
<pre>
~/.local/share/Serious-Engine/serioussam/ - for TFE
~/.local/share/Serious-Engine/serioussamse/ - for TSE
</pre>

**Comment by tx00100xt** [comment] 2023-05-08 19:21
I don't use gnome. When you try to google this problem, you can see that it occurs in different games.
https://www.reddit.com/r/Fedora/comments/uoq111/black_line_on_right_side_in_full_screen_apps/
https://www.reddit.com/r/gnome/comments/uqei9k/black_line_on_right_side_in_full_screen_apps/

The solution to the problem is described here. Need to set gnome dock to auto-hide in full screen mode
https://www.reddit.com/r/ManjaroLinux/comments/rkmrfu/gnome_dock_keeps_popping_through_full_screen/

**Comment by LethalManBoob** [comment] 2023-05-08 21:10
I should note that i am using dash to dock.  The black line is the actual header, just turned black.

**Comment by LethalManBoob** [comment] 2023-05-08 21:30
afaik this only started happening since gnome 44

**Comment by tx00100xt** [comment] 2023-05-09 07:40
If you look at the log, you can see that the game is launched in full screen mode and at the correct resolution.

>* START NEW DISPLAY MODE...
>   Starting display mode: 1920x1080xdesktop (fullscreen)
>Multimonitor is not supported on this platform.
>

The screenshot shows another resolution of 1920x1043,
https://gitlab.gnome.org/GNOME/mutter/-/issues/2678
As you can see, this problem has affected more than one game. And although they closed the issue, people still write that their corrections do not help. This is the problem of the gnome itself and not the game.
Let's hope that the gnome developers will fix this problem.

I'll try to install a system with gnome in my free time and see what can be done. But I do not promise the result, since this is the problem of the gnome, not the game.

**Comment by LethalManBoob** [comment] 2023-05-09 21:56
Yes i can confirm i had the issue with l4d2 recently. Go figure gnome would mess up this bad.

**Comment by tx00100xt** [comment] 2023-05-22 12:54
I installed gnome 4 on a virtual machine. The result is the same:

![Screenshot from 2023-05-22 15-28-07](https://github.com/tx00100xt/SeriousSamClassic-VK/assets/105300480/765f7684-6e32-427e-8869-33cd49aeda3d)

The black stripe is both below and above. The correct resolution of 1920-1080 was set several times when changing the video settings. Then again with a black stripe. I looked at all the code - responsible for window sizes and display modes - everything is correct in it. As I understand it, when switching from 43 to 44 gnomes, many changes were made and errors appeared that people still face today. They broke the proper functioning of windows in gnome

https://gitlab.gnome.org/GNOME/mutter/-/issues/2678
https://www.reddit.com/r/gnome/comments/13i3qt5/removing_title_bars_in_gnome_44/
https://discussion.fedoraproject.org/t/odd-black-frame-around-some-windows-in-gnome-44-on-f38/81795
https://www.reddit.com/r/Fedora/comments/132wj8s/how_can_i_remove_this_black_line_for_maximized/
https://www.reddit.com/r/gnome/comments/13acwv3/black_bars_and_boxes_around_applications_in_gnome/
https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/5857
https://bugzilla.redhat.com/show_bug.cgi?id=2178167
https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/2011803

It remains only to wait for the developers of the gnome to fix them.

**Comment by tx00100xt** [comment] 2023-05-22 14:11
Once again, finally, I decided to read the topic https://gitlab.gnome.org/GNOME/mutter/-/issues/2678
And I tried to add an additional flag (`SDL_WINDOW_BORDERLESS`) when creating a SDL WIindow. As indicated here: https://gitlab.gnome.org/GNOME/metacity/-/issues/11
The error is gone. The game starts correctly. Although the presence of this flag when creating a window is not necessary.

Now I will commit to the fix in the repository

**Comment by LethalManBoob** [comment] 2023-05-22 14:31
ah great to see. gnome 44 really shit the bed

**Comment by LethalManBoob** [comment] 2023-05-22 15:07
Thanks a bunch. also the mods as well if that needs updating of course. Loving the project so far. Is there anyway to boot with a particular mod btw?

**Comment by tx00100xt** [comment] 2023-05-22 16:38
In mods only libraries. There is no need to fix it. The general fix will also affect mods.

You can run the mod from the command line.
>serioussam-tfe +game SSA
>
Launch the Alpha Remake mod
>serioussam-tse +game XPLUS
>
Launch the XPLUS mod for TSE

The mod names correspond to the names of the directories in the Mods directory.
> Loving the project so far.
>
Thanks.

>And I dont want to keep on but is there anyway you can double the size of the weapon hud sprites so they dont get cut off in >the hud? Its the last issue i have with this port
>
I'll think about it

**Comment by tx00100xt** [comment] 2023-05-22 20:25
https://aur.archlinux.org/cgit/aur.git/log/?h=serioussam
https://aur.archlinux.org/cgit/aur.git/log/?h=serioussam-vk

Can be checked.

**Comment by LethalManBoob** [comment] 2023-05-22 21:32
Seems far more responsive and snappy when alt tabbing ontop of fixing the bug. Good stuff!

**Comment by tx00100xt** [comment] 2023-05-23 07:09
When checking the bug completely disappeared. Normal resolution is set and there is no need to press Alt Enter. Works the same as in the desktop mate. Checked up on two virtual machines with the gnome. The black bar is no more.

![Снимок экрана в 2023-05-22 23-49-39](https://github.com/tx00100xt/SeriousSamClassic-VK/assets/105300480/25743dee-1f82-4ff8-b58d-d0c591b5ba98)

![Снимок экрана в 2023-05-23 09-58-16](https://github.com/tx00100xt/SeriousSamClassic-VK/assets/105300480/7957427f-e33e-4e6b-bb9a-42cc906d36d8)

**Comment by tx00100xt** [comment] 2023-05-23 09:18
Today I added 3 more mods in Aur:
https://aur.archlinux.org/packages/serioussam-st8vi
https://aur.archlinux.org/packages/serioussam-st8vipe
https://aur.archlinux.org/packages/serioussam-hno

https://github.com/tx00100xt/SE1-TSE-ST8VI
https://github.com/tx00100xt/SE1-TSE-ST8VIPE
https://github.com/tx00100xt/SE1-TSE-HNO

Mod HNO is better to use with opengl.

If the problem with the wrong resolution and the black bar is also solved for you, then I think the issue can be closed.

**Comment by LethalManBoob** [comment] 2023-05-23 09:42
btw alpha mod in aur has broken text in some places in the menu

**Comment by tx00100xt** [comment] 2023-05-25 08:32
> btw alpha mod in aur has broken text in some places in the menu
>
 Fixed: https://aur.archlinux.org/cgit/aur.git/commit/?h=serioussam-alpha&id=7952b8ebba1d80e731d36cf90fe8a62d290f0554
>ill test the other mods
>
Mod https://aur.archlinux.org/packages/serioussam-hno also contains non-english characters
I will do it when I have free time.

Since the main problem indicated in the issue is solved. I am closing this issue.

**Closed by tx00100xt** 2023-05-25 08:32 UTC
